spring.application.name=gym-training-app

app.security.password.characters=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()
app.security.password.default-length=10

management.endpoints.web.exposure.include=health,metrics

management.endpoint.health.show-details=always
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gym_management_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:my_local_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
#spring.sql.init.mode=always

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
